spring:
  application:
    name: hotel-pms
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/h2/hotel-db
  jpa:
    hibernate:
      ddl-auto: create
